### ISSUE TITLE
[lua error]

### ISSUE THREAD

**Issue by Altoholic** [rainfordays/Restocker#11]
It happened while i was auto buying reagents (vials) from an alchemist vendor.
No vial was bought.

2x Restocker\Poisons.lua:119: bad argument #1 to 'pairs' (table expected, got nil)
[C]: in function `pairs'
Restocker\Poisons.lua:119: in function `getPoisonReagents'
Restocker\Events.lua:86: in function `?'
Restocker\Events.lua:28: in function <Restocker\Events.lua:27>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by Altoholic** [comment]
update: it also happen when i'm full on vials, and don't need to buy more.

**Comment by rainfordays** [comment]
you can change this locally (will be in a future update)

poisons.lua > line 99

add 
`if select(2, UnitClass("PLAYER")) ~= "ROGUE" then return {} end`

right below the `function RS:getPoisonReagents()` so it looks like this

```
function RS:getPoisonReagents()
  if select(2, UnitClass("PLAYER")) ~= "ROGUE" then return {} end
  
  local T = {}
```
