### ISSUE TITLE
[bug] checked options auto uncheck at each login

### ISSUE THREAD

**Issue by Altoholic** [rainfordays/Restocker#13]

**Comment by MatthlK** [comment]
Same here. Auto Buy setting unchecks.

**Comment by zazomazzo** [comment]
Just want to confirm. Auto Buy not saving. Gets reset even after reload ui.

**Comment by rainfordays** [comment]
This was super fucking weird cus it was something that was supposed to be fixed in the  6.1.2 release but the automatic package manager somehow reuploaded the 6.1.1.

I pushed a new version that fixes this.
