### ISSUE TITLE
Items with suffix enhancements not handled correctly

### ISSUE THREAD

**Issue by metzen** [rainfordays/Restocker#14]
Items with a suffix enhancement (e.g., [Master's Mantle of Shadow Wrath](https://classic.wowhead.com/item=10253/masters-mantle), [Peridot Circle of Fire Resistance](https://classic.wowhead.com/item=11979/peridot-circle)) have noticeable issues with features in Restocker depending on which method is used to add the item to a profile item list.

1. Attempting to drag-and-drop a suffix item into the "Add Item" edit box produces no result.
2. Using the Shift+Click method of adding a suffixed item does add the item to the list (including the suffix), and correctly pulls the item from the bank when given a value >= 1. However, when given a value of 0, restocker fails to move the item from inventory into the bank.
3. Manually entering a suffix item name into the "Add Item" edit box results in a non-suffixed version of the item added to the list. Although this does correctly move items both to and from the bank, I suspect this would be problematic if a user possesses multiple suffix versions of a suffixed item, as it would not be possible to configure restocking behavior per item suffix type.

Most of the problems here seem to stem from the fact that the item name returned by a `GetItemInfo()` call for a suffixed item will simply be the base item name (not including suffix) when the lookup is performed using either the item name or item ID e.g.,

```
>>> GetItemInfo(11979)
'Peridot Circle', [Peridot Circle], ...
>>> GetItemInfo('Peridot Circle of Fire Resistance')
'Peridot Circle', [Peridot Circle], ...
```

However, `GetItemInfo()` also accepts an `itemlink` argument for performing lookups, which will return a suffixed version of the item since the suffixId information is present within the `itemLink` (really, the `itemString` within it).

```
>>> GetItemInfo('[Peridot Circle of Fire Resistance]')
'Peridot Circle of Fire Resistance', [Peridot Circle of Fire Resistance]', ...

**Comment by rainfordays** [comment]
Yeah, i was lazy when doing it because the itemstring also contains the itemlevel which if used would make the restocking super picky about everything.

**Comment by rainfordays** [comment]
Just pushed an update that should fix  this issue. Now tries using the exact item name in all situations.

You have to shift-click add items with a suffix, when getting an itemlink or itemname for plain text it only takes the base name because the text `Peridot Circle of Fire Resistance` contains no information about the suffix OR the itemlevel of the suffix.

Drag-and-drop adding has also been fixed.
