### ISSUE TITLE
[bug] Auto sell crafted poisons poisons to vendor

### ISSUE THREAD

**Issue by Altoholic** [rainfordays/Restocker#2]
Not exactly a bug, but a major concern: when you put poisons to 0 (i use that after a raid, putting back to bank a lot of stuff), if it's in your bag when you visit a merchant, it sell it.

So, i like the auto-buy feature (i use it with flash powder, i have not see another use for it for now), but i really fear the auto-sell (i think that should be disabled by default - if not totally removed; there's already a lot of addons that can auto-sell stuff).

Edit: i can't reproduce the bug 100%. That's weird (my auto-sell addon, leatrix plus, only sell grays, for information).

Edit2: i can reproduce it 100%. I tried this time with a totally unrelated item: a mining pick. I put it to zero in a profile. It's when i switch to that profile while the merchant window is open that the selling happen.

Edit3: disabling the "auto buy items" feature don't prevent the selling.

**Comment by rainfordays** [comment]
Thank you for posting this, there isn't any auto-sell feature in the addon but the behaviour you describe is an unintended sideeffect of switching profiles  while the restocking window is open.

I will post a fix for this immediately.
