### ISSUE TITLE
Multiple attempts at failed action

### ISSUE THREAD

**Issue by Klaveback** [rainfordays/Restocker#3]
For example when opening the bank and you empty you bags into the bank, when it is full is keeps trying to empty the bag spamming errors. "Your bank is full"

Possibly add a maximum of 5 attempts or less, before stopping the trying of shuffle stuff around?

And when have an "empty bags" profile active and try to reshuffle stuff into my bags the addon keeps shoveling the items back if they are on the list as "0pcs". This could be avoided if it only tries a few times and then stops. Then if you close/open the bank again it reshuffle again, that's fine since no profile change was made.

I don't know if it is possible to detect bank opening/closing?

**Comment by rainfordays** [comment]
Fixed in 9a6042fe0bca8a19edd466b6b5c434de23906d25
