### ISSUE TITLE
"of healing" gear not loading/unloading

### ISSUE THREAD

**Issue by Avienated** [rainfordays/Restocker#5]
I have 5 pieces of "of healing" gear (from random rolls). None of it seems to load from bank or unload to bank.
Items:
Commander's Girdle of Healing
High Councillor's Circle of Healing
Elegant Bracers of Healing
etc.

**Comment by rainfordays** [comment]
Should be fixed in next release.

**Comment by rainfordays** [comment]
If youd like this functionality right away you can replace all the text in Restocker/Helpers/Bank.lua with the text from the following link
https://raw.githubusercontent.com/rainfordays/Restocker/master/Helpers/Bank.lua

**Comment by Avienated** [comment]
Swift and perfect service, impressive! Works like a charm now.
