### ISSUE TITLE
[feature request] "all in" / "all out" button near each item

### ISSUE THREAD

**Issue by Altoholic** [rainfordays/Restocker#6]
So i can quickly put in or out very larges quantities of items (very useful as a crafter - i currently just put o or 99999 to have the same result, but i have to close and open bank each time).

**Comment by rainfordays** [comment]
Make different profiles, changing profiles while bank is open will trigger the addon to restock/deposit items.

**Comment by Altoholic** [comment]
Unfortunately, i will need a profile for each item, which will be hundreds of profiles ! XD

**Comment by rainfordays** [comment]
You should create a profile for each prof or category of craft and then have one which deposits all. The reason why I wont implement it is because it would add clutter to an already pretty cluttered UI
