### ISSUE TITLE
Only buying 1 type of vendor item at the time

### ISSUE THREAD

**Issue by Avienated** [rainfordays/Restocker#7]
I get this bug from Jekyll Flandring outside AV. The first time I trade with him, Alterac Heavy Runecloth Bandage is restocked. I then have to exit vendor window and click him again, for Major Healing Draught to restock.

**Comment by rainfordays** [comment]
This is the first I've heard of this and havn't experienced it myself so quite hard to troubleshoot. Will try replicating but can't promise anything in terms of updates or fixes anytime soon.
