### ISSUE TITLE
filling the bank

### ISSUE THREAD

**Issue by Sigma88** [rainfordays/Restocker#8]
When I have more than the requested amount of a certain item, restock puts the excess from my bag to the bank.

is it possible to disable this feature?

**Comment by rainfordays** [comment]
You could hold shift when opening the bank to disable the restocking behaviour.

**Comment by Sigma88** [comment]
It would be great if there was an option to disable that behaviour, I can try to remember to hold shift but it's bound to happen before or later that I forget and then have to take everything out of the bank :D
