### ISSUE TITLE
Feature Request: flag to disable bank restock function

### ISSUE THREAD

**Issue by cracklingice** [rainfordays/Restocker#9]
I wish to use this addon to restock arrows on my hunter, but he is also my alchemist.  When I am restocking my potions (to craft and list on the AH), I put my quiver in the bank in favor of an empty bag for more space; but then this addon fights my desired outcome by pulling all the arrows out of my bank.

**Comment by rainfordays** [comment]
Hold shift when you open bank to stop restocker from functioning

OR

Make a new profile for Alchemy where you have your arrows set to 0.

Any item with the amount set to 0 will deposit all of those items to the bank.

**Comment by cracklingice** [comment]
Thank you for the prompt reply.  I could not find a way to modify configuration settings.

**Comment by rainfordays** [comment]
Sorry, latest version contains a new checkbox in the main window that toggles banking operations. I would still advise you to actually make a profile specifically for alchemy.
